<?php

/***************************************************************
* Extension Manager/Repository config file for ext "Cool".
*
* Auto generated by ext 16-03-2013 18:44
*
* Manual updates:
* Only the data in the array - everything else is removed by next
* writing. "version" and "dependencies" must not be touched!
***************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'version' => '9.9.9',
);

?>